version: '2.1'
services:
  kotlin-user-service:
    build: kotlin-user-service
    image: kotlin-user-service
    depends_on:
      - kotlin-mongo
    environment:
      JAVA_OPTS: -Dmongo.host=kotlin-mongo -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n
    ports:
      - "${KOTLIN_USER_SERVICE_DEBUG_PORT:-1045}:1044"
  kotlin-api-gateway:
    build: kotlin-api-gateway
    image: kotlin-api-gateway
    depends_on:
      - kotlin-user-service
    environment:
      JAVA_OPTS: -Duser.service.url=kotlin-user-service:8080 -agentlib:jdwp=transport=dt_socket,server=y,address=1044,suspend=n
    ports:
      - "8080:8080"
      - "${KOTLIN_API_GATEWAY_DEBUG_PORT:-1044}:1044"
  kotlin-mongo:
    image: mongo
    ports:
      - "27017:27017"